# Copyright 2021-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0
---
- name: Transfer kubeconfig from master to tester
  synchronize:
    src: /home/vagrant/.kube
    dest: /home/vagrant/.kube
  delegate_to: kubemaster
