# Copyright 2021-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: int-watchlist
  labels:
    app: int-host-reporter
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  watchlist.yaml: |
    rules:
    {{- range .Values.intWatchlistRules }}
    - protocol: "{{ .protocol }}"
      src-addr: "{{ .srcAddr }}"
      dst-addr: "{{ .dstAddr }}"
    {{- end }}